# Generated by Django 3.1.4 on 2021-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210121_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='https://leetcode.com/problemset/all/', max_length=200),
        ),
    ]
